#!/usr/bin/env python3
"""Traceability tooling: the coverage ledger, the slice queue, and the process checks.

Generated by the `bootstrap` kit. Stdlib only, Python 3.9+.

    python3 scripts/ledger.py                    write the ledger and the queue block
    python3 scripts/ledger.py ledger [--check]   just the coverage ledger
    python3 scripts/ledger.py queue  [--check]   just the generated queue block
    python3 scripts/ledger.py check              verify both, plus every process check — CI runs this

The contract, in one paragraph. `ID-REGISTRY.md` declares identifier *families* — never
identifiers. Each family names the document and the section that declares its IDs. An identifier
is declared if and only if it is the first cell of a table row, under a header row beginning
`| ID |`, inside that section. Work orders claim IDs in their YAML frontmatter. Tests prove them
by carrying `[ID]` in a test name. This tool joins the four sources and writes the result down.

Nothing here knows a prefix. Adding a family is a Markdown row, never a code change.

Two more sources are checked and never counted. `requirements.dir` holds one detail file per
requirement — what it means, told as stories — and `scenarios.dir` holds the manual test scenarios
written from that file. Neither changes a status: a requirement is proven by its tests. But each
quotes its requirement verbatim, and this verifies the quote, so an amended specification fails
every file that has not been re-read.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from dataclasses import dataclass, field

# --------------------------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------------------------

DEFAULTS = {
    "project": "",
    "mode": "solo",
    "registry": "canon/spec/ID-REGISTRY.md",
    "work_orders": "canon/process/work-orders",
    "slices": "canon/process/slices",
    "decisions": "canon/decisions",
    "coverage_out": "canon/process/COVERAGE.md",
    "queue_out": "canon/process/SLICE-QUEUE.md",
    "tests": {
        "globs": ["**/*.test.*", "**/test_*.py", "**/*_test.go"],
        "exclude": ["**/node_modules/**", "**/.venv/**", "**/dist/**", "**/build/**"],
        "annotation": r"\[(?P<id>[A-Za-z][A-Za-z0-9]*(?:-[A-Za-z0-9.]+)+)\]",
    },
    "placeholder_scan": {
        "include": ["canon/**/*.md", "CLAUDE.md", "README.md"],
        "exclude": ["canon/process/templates/**", "canon/decisions/template.md"],
    },
    "phases": [],
    "wip_limit": 0,
    # Whether a claimed slice is mirrored by a tracker issue as well as by its work order. `github`
    # is the one the skills know how to drive; empty turns it off and the queue loses its Issue
    # column. On, `issue:` is required from the moment a slice is claimed — see `check_process`.
    "tracker": "",
    # The detail track is off until a project installs it: an empty `dir` means the checks below
    # never run, so a project that declined it is not failed for a directory it does not have.
    "requirements": {
        "dir": "",
        "families": [],
        "phase_pattern": "V1|V2|R",
        "require_detail_for_satisfied": False,
    },
    # The manual test scenario track sits a step behind the detail track and is switched off the
    # same way. It reads the detail files, so a project running this without those has every
    # scenario file failing for the source it does not have. `commands` names the project's own
    # command-line tools, so a scenario that asks the tester to run one is caught by name.
    "scenarios": {
        "dir": "",
        "families": [],
        "commands": [],
        "require_scenarios_for_reviewed_detail": False,
    },
}

QUEUE_BEGIN = "<!-- generated:queue -->"
QUEUE_END = "<!-- /generated -->"

SATISFIED, PARTIAL, NONE = "satisfied", "partial", "none"
MARK = {SATISFIED: "●", PARTIAL: "◐", NONE: "○"}


def load_config(root: str, path: str) -> dict:
    """Read `scripts/ledger.config.json`, merged one level deep over the defaults."""
    merged = json.loads(json.dumps(DEFAULTS))
    full = os.path.join(root, path)
    if os.path.exists(full):
        with open(full, encoding="utf-8") as handle:
            raw = json.load(handle)
        for key, value in raw.items():
            if isinstance(value, dict) and isinstance(merged.get(key), dict):
                merged[key].update(value)
            else:
                merged[key] = value
    return merged


# --------------------------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------------------------


def bare(cell: str) -> str:
    """Strip emphasis and code fencing from a table cell so `**INV-1**` reads as `INV-1`."""
    return cell.replace("*", "").replace("`", "").strip()


def normalise(heading: str) -> str:
    """Lowercase, alphanumerics only — so `§9 Functional requirements` finds `## 9. Functional
    requirements`. The registry stays readable; the matcher does the work."""
    return re.sub(r"[^a-z0-9]", "", heading.lower())


def cells(line: str) -> list:
    """Split a Markdown table row into its cells."""
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    return [c.strip() for c in body.split("|")]


def is_separator(line: str) -> bool:
    return bool(re.match(r"^\s*\|[\s:|-]+\|\s*$", line))


def escape(text: str) -> str:
    return text.replace("|", "\\|").strip()


def headings(lines) -> list:
    """(index, level, title) for every heading, ignoring anything inside a fenced code block.

    A shell comment inside a ```bash block matches the heading pattern exactly. Reading one as a
    heading truncates whatever section it sits in, which is how a demo script full of `#` comments
    becomes an empty demo section."""
    found, fenced = [], False
    for index, line in enumerate(lines):
        if re.match(r"^\s*(```|~~~)", line):
            fenced = not fenced
            continue
        if fenced:
            continue
        head = re.match(r"^(#{1,6})\s+(.*)$", line)
        if head:
            found.append((index, len(head.group(1)), head.group(2)))
    return found


def read(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def iter_files(root: str, includes, excludes=()) -> list:
    """Expand glob patterns relative to `root`, deterministically, honouring exclusions."""
    excluded = set()
    for pattern in excludes:
        excluded.update(glob.glob(os.path.join(root, pattern), recursive=True))
    found = set()
    for pattern in includes:
        for hit in glob.glob(os.path.join(root, pattern), recursive=True):
            if os.path.isfile(hit) and hit not in excluded:
                found.add(hit)
    return sorted(found)


# --------------------------------------------------------------------------------------------
# A minimal YAML front-matter reader
# --------------------------------------------------------------------------------------------
#
# Deliberately not a YAML implementation. Work-order front matter is scalars, inline lists and
# block lists, and nothing else — a restriction the template states and this parser enforces by
# not understanding anything more. A dependency for eight fields would be the wrong trade.


def strip_comment(raw: str) -> str:
    """Drop a trailing `# ...` comment, as YAML does — a `#` opens one only after whitespace.

    The templates carry an aligned comment on half their front-matter lines (`status: queued
    # queued | in-progress | ...`), so a drafter who fills one in and leaves the comment is doing
    the obvious thing. Without this, `status` reads as the whole line and every check that compares
    it silently stops working."""
    value = raw.strip()
    if value[:1] in ("\"", "'"):
        end = value.find(value[0], 1)
        if end != -1:
            return value[: end + 1]
        return value
    cut = re.search(r"(?:^|\s)#", value)
    return value[: cut.start()].strip() if cut else value


def parse_scalar(raw: str):
    value = strip_comment(raw)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value in ("true", "false"):
        return value == "true"
    if value in ("null", "~", ""):
        return None
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def parse_front_matter(text: str):
    """Return (mapping, body). A file with no front matter yields ({}, text)."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}, text
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        return {}, text

    data: dict = {}
    key = None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s*-\s+(.*)$", line)
        if item and key is not None:
            data.setdefault(key, [])
            if isinstance(data[key], list):
                data[key].append(parse_scalar(item.group(1)))
            continue
        pair = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$", line)
        if not pair:
            continue
        key, raw = pair.group(1), strip_comment(pair.group(2))
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            data[key] = [parse_scalar(p) for p in inner.split(",")] if inner else []
        elif raw == "":
            data[key] = []
        else:
            data[key] = parse_scalar(raw)
    return data, "\n".join(lines[end + 1 :])


def as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value if v not in (None, "")]
    return [str(value)] if str(value) else []


# --------------------------------------------------------------------------------------------
# Source 1 — the registry
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Family:
    family: str
    pattern: str
    owner: str
    section: str
    kind: str
    traceable: bool


def parse_registry(text: str) -> list:
    """Read the `| Family | Pattern | Owner | Declared in | Kind | Traceable |` table."""
    families = []
    for line in text.split("\n"):
        if not line.strip().startswith("|") or is_separator(line):
            continue
        col = cells(line)
        if len(col) < 6:
            continue
        name = bare(col[0])
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name) or name.lower() == "family":
            continue
        families.append(
            Family(
                family=name,
                pattern=bare(col[1]),
                owner=bare(col[2]),
                section=bare(col[3]),
                kind=bare(col[4]),
                traceable="yes" in col[5].lower(),
            )
        )
    return families


# --------------------------------------------------------------------------------------------
# Source 2 — declared identifiers
# --------------------------------------------------------------------------------------------


def section_lines(text: str, section: str) -> list:
    """The lines of `section`, from its heading to the next heading of the same or higher level.

    Subsections are included and siblings are not. A section of `*` is the whole document."""
    lines = text.split("\n")
    if section.strip() == "*":
        return lines
    want = normalise(section)
    start = None
    level = 0
    for index, depth, raw in headings(lines):
        title = normalise(raw)
        if start is None:
            if title == want or title.startswith(want) or (title and want.startswith(title)):
                start, level = index, depth
            continue
        if depth <= level:
            return lines[start + 1 : index]
    return [] if start is None else lines[start + 1 :]


def declared_rows(text: str, section: str) -> list:
    """(identifier, cells) for every declaring row, in document order.

    The whole row rather than its first cell, because the requirement's own words are the second
    cell and the detail track quotes them verbatim. Nothing else may restate a requirement: a
    second wording of one is a second requirement, discovered the day the two disagree."""
    found, in_table = [], False
    for line in section_lines(text, section):
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        if is_separator(line):
            continue
        col = cells(line)
        if not col:
            continue
        first = bare(col[0])
        if first.lower() == "id":
            in_table = True
            continue
        if in_table and first:
            found.append((first, col))
    return found


def declared_ids(text: str, section: str) -> list:
    """Every first-cell value of a table whose header row begins `| ID |`, inside `section`."""
    return [ident for ident, _cells in declared_rows(text, section)]


# --------------------------------------------------------------------------------------------
# Source 3 — work-order claims
# --------------------------------------------------------------------------------------------


@dataclass
class WorkOrder:
    path: str
    slice_id: str
    title: str = ""
    phase: str = ""
    size: str = ""
    status: str = "queued"
    dep: str = "—"
    owner: str = ""
    depends_on: list = field(default_factory=list)
    touches: list = field(default_factory=list)
    satisfies: list = field(default_factory=list)
    partial: list = field(default_factory=list)
    adr: list = field(default_factory=list)
    demo: str = ""
    issue: str = ""
    body: str = ""


def slice_paths(root: str, config: dict, order) -> list:
    """Where a slice's summary may live: mirroring its work order's place in the tree.

    Mirroring rather than flattening is what keeps the two halves of one slice together as the
    directory grows a milestone and a phase level. A flat directory of sixty summaries is the
    thing this layout exists to prevent, and putting the summaries back into one would recreate
    it."""
    sub_dir = os.path.dirname(os.path.relpath(order.path, config["work_orders"]))
    base = os.path.join(root, config["slices"], sub_dir)
    return [
        os.path.join(base, order.slice_id + ".md"),
        os.path.join(base, order.slice_id.split("-")[-1] + ".md"),
    ]


def parse_work_orders(root: str, directory: str) -> list:
    orders = []
    # Recursive: work orders sit under `<milestone>/<phase>/`, and a flat directory still works
    # so the layout can be adopted without moving anything first.
    for path in sorted(glob.glob(os.path.join(root, directory, "**", "*.md"), recursive=True)):
        data, body = parse_front_matter(read(path))
        if not data:
            continue
        stem = os.path.splitext(os.path.basename(path))[0]
        orders.append(
            WorkOrder(
                path=os.path.relpath(path, root),
                slice_id=str(data.get("id") or stem),
                title=str(data.get("title") or ""),
                phase=str(data.get("phase") or ""),
                size=str(data.get("size") or ""),
                status=str(data.get("status") or "queued"),
                dep=str(data.get("dep") or "—"),
                owner=str(data.get("owner") or ""),
                depends_on=as_list(data.get("depends_on")),
                touches=as_list(data.get("touches")),
                satisfies=as_list(data.get("satisfies")),
                partial=as_list(data.get("partial")),
                adr=as_list(data.get("adr")),
                demo=str(data.get("demo") or ""),
                issue=str(data.get("issue") or "").lstrip("#").strip(),
                body=body,
            )
        )
    return orders


# --------------------------------------------------------------------------------------------
# Source 4 — test annotations
# --------------------------------------------------------------------------------------------

QUOTED = re.compile(r"""(['"`])(.*?)\1""")


def parse_annotations(root: str, tests: dict) -> list:
    """Every `[ID]` occurrence in a test file, with the enclosing test name as its proof.

    Parsing source text is deliberate: this reports what the suite *claims* to prove. That the
    suite passes is a separate gate step, and conflating the two would let a skipped test count
    as evidence without anyone noticing which of the two failed."""
    pattern = re.compile(tests["annotation"])
    hits = []
    for path in iter_files(root, tests["globs"], tests.get("exclude", [])):
        rel = os.path.relpath(path, root)
        try:
            content = read(path)
        except (UnicodeDecodeError, OSError):
            continue
        for line in content.split("\n"):
            for match in pattern.finditer(line):
                ident = match.group("id")
                proof = match.groupdict().get("proof")
                if not proof:
                    quoted = [q.group(2) for q in QUOTED.finditer(line) if "[" + ident + "]" in q.group(2)]
                    proof = quoted[0] if quoted else line.strip()
                hits.append((ident, proof.strip(), rel))
    return sorted(set(hits))


# --------------------------------------------------------------------------------------------
# Source 5 — requirement detail files
# --------------------------------------------------------------------------------------------
#
# One file per requirement, saying what a person would *see* if it held. It is not a coverage
# source — a requirement is proven by its tests — but it is what a manual test case is written
# from, and what a verification run judges against. Nothing else fills that gap: a slice spans
# several requirements and proves its own claims, not theirs.
#
# The whole risk of a second document per requirement is that it becomes a second specification
# which quietly disagrees with the first. Hence the quote: a detail file carries the requirement's
# own words, character for character, and this checks them. When the specification is amended the
# file fails until somebody has read the amendment.

DETAIL_STATUSES = ("draft", "reviewed")
DETAIL_VERDICTS = ("implemented", "gap", "absent", "detail-wrong")
# `revised_on` is the last day the file's claims changed. It is what lets a scenarios file know it
# was read before an amendment: `status` only moves once, at approval, and the quote only moves
# when the specification does, so without a date an amended reviewed file would fail nothing.
DETAIL_KEYS = ("id", "area", "status", "drafted_by", "approved_by", "reviewed_against", "revised_on", "surface")
# The first entry is load-bearing twice over: `quoted()` reads the blockquote under it, and that
# blockquote is what is compared to the specification character for character. Moving it means
# changing both.
DETAIL_SECTIONS = (
    "The requirement",
    "Summary — the job to be done",
    "Personas",
    "Mandatory and non-mandatory fields",
    "Preconditions and data",
    "Observable behaviour",
    "Boundary and negative cases",
    "Out of scope",
    "Open questions",
    "Related",
    "Verification",
)

# **A file with no story in it has not understood its requirement yet.** The stories are the
# primary content of a detail file, and they are the half that would quietly stop being written if
# nothing asked for it — every other section has a shape a drafter falls into, and a story does
# not.
#
# Matched against the *normalised* heading, which is alphanumerics only — so `## Story 1 — the
# walk-in` arrives here as `story1thewalkin` and there is no word boundary after `story` to anchor
# on. The digit is what distinguishes a story from a section that merely starts with the word.
STORY_HEADING = re.compile(r"^story\d")
BLANK = (None, "", "-", "—", "TBD", "tbd")


@dataclass
class Detail:
    path: str
    ident: str
    data: dict
    body: str


def area_of(ident: str) -> str:
    """`FR-ACC-01` files under `FR-ACC`, `INV-1` under `INV`. The directory is derived from the
    identifier, so it is one less thing to keep in step."""
    return ident.rsplit("-", 1)[0]


def scalar(value) -> str:
    """Front matter yields a list for an empty value and for a bracketed one. Either way a field
    that names nobody reads as blank."""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return "" if value is None else str(value)


def parse_details(root: str, directory: str) -> list:
    if not directory:
        return []
    details = []
    for path in sorted(glob.glob(os.path.join(root, directory, "**", "*.md"), recursive=True)):
        if os.path.basename(path).lower() == "readme.md":
            continue
        data, body = parse_front_matter(read(path))
        details.append(
            Detail(
                path=os.path.relpath(path, root),
                ident=os.path.splitext(os.path.basename(path))[0],
                data=data,
                body=body,
            )
        )
    return details


def quoted(body: str) -> str:
    """The blockquote under *The requirement*, unwrapped to one line.

    Joined and whitespace-collapsed so that wrapping a long requirement across several `>` lines
    is a formatting choice rather than a failure."""
    want, inside, lines = normalise(DETAIL_SECTIONS[0]), False, []
    for line in body.split("\n"):
        if line.lstrip().startswith("#"):
            if lines:
                break
            inside = normalise(line.lstrip("#")) == want
            continue
        if inside and line.strip().startswith(">"):
            lines.append(line.strip()[1:].strip())
        elif lines and not line.strip():
            break
    return re.sub(r"\s+", " ", " ".join(lines)).strip()


def section_titles(body: str) -> list:
    return [normalise(t) for _i, depth, t in headings(body.split("\n")) if depth == 2]


def verification_verdicts(body: str) -> list:
    """The second cell of every row under *Verification*, which is where a run records what it
    found. A vocabulary rather than prose: *mostly works* is the verdict this exists to refuse."""
    found, in_table = [], False
    for line in section_lines(body, DETAIL_SECTIONS[-1]):
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        if is_separator(line):
            continue
        col = cells(line)
        if len(col) < 2:
            continue
        if bare(col[0]).lower() == "date":
            in_table = True
            continue
        if in_table and bare(col[0]):
            found.append(bare(col[1]))
    return found


def check_details(config: dict, data: Collected, satisfied: set) -> list:
    """Every way a detail file can be wrong about the requirement it names."""
    spec = config.get("requirements") or {}
    directory = spec.get("dir") or ""
    if not directory:
        return []

    families = [str(f) for f in (spec.get("families") or [])]
    eligible = {i for fam, ids in data.ids.items() for i in ids if not families or fam in families}
    phase_pattern = str(spec.get("phase_pattern") or "")
    errors = []

    for detail in data.details:
        where = detail.path + ": "
        if not detail.data:
            errors.append(where + "has no front matter")
            continue

        ident = detail.ident
        if scalar(detail.data.get("id")) != ident:
            errors.append(where + "declares id " + scalar(detail.data.get("id")) + " and is filed as " + ident)
        if ident not in eligible:
            # Two different mistakes, and the difference matters: a withdrawn requirement is
            # struck through and thereby undeclared, so its file has outlived it.
            declared = {i for ids in data.ids.values() for i in ids}
            if ident in declared:
                errors.append(where + ident + " belongs to no family the detail track covers (" + ", ".join(families) + ")")
            else:
                errors.append(where + ident + " is not declared in the specification")
            continue

        area = area_of(ident)
        leaf = os.path.basename(os.path.dirname(detail.path))
        if leaf != area:
            errors.append(where + "sits under " + leaf + " and its identifier files under " + area)
        if scalar(detail.data.get("area")) != area:
            errors.append(where + "declares area " + scalar(detail.data.get("area")) + " and its identifier files under " + area)

        # `approved_by` is the exception: a draft has no approver, and the pair is checked below.
        for key in (k for k in DETAIL_KEYS if k != "approved_by"):
            if scalar(detail.data.get(key)).strip() in BLANK:
                errors.append(where + "front matter has no " + key)

        status = scalar(detail.data.get("status"))
        if status not in DETAIL_STATUSES:
            errors.append(where + "status is " + (status or "empty") + ", not one of " + ", ".join(DETAIL_STATUSES))
        if status == "reviewed" and scalar(detail.data.get("approved_by")).strip() in BLANK:
            errors.append(where + "is reviewed and names no approver — a review nobody signed is a draft")

        row = data.rows.get(ident) or []
        source = bare(row[1]) if len(row) > 1 else ""
        # `bare` on both sides, or a requirement whose row carries emphasis could never be quoted
        # verbatim: the cell arrives stripped and the blockquote would not be.
        if source and re.sub(r"\s+", " ", source) != bare(quoted(detail.body)):
            errors.append(
                where + "quotes " + ident + " differently from the specification. The requirement "
                "was amended, or the quote was edited — re-read it, correct the quote and re-date "
                "reviewed_against"
            )
        # Whatever the declaring table uses to phase its requirements, mirrored. A table that
        # carries no such column — an invariant's, typically — is simply not checked.
        phase = ""
        if phase_pattern:
            phase = next((bare(c) for c in row[1:] if re.fullmatch(phase_pattern, bare(c))), "")
        if phase and scalar(detail.data.get("phase")) != phase:
            errors.append(
                where + "says " + (scalar(detail.data.get("phase")) or "no phase")
                + " and the specification says " + phase
            )

        present = section_titles(detail.body)
        for title in DETAIL_SECTIONS:
            if normalise(title) not in present:
                errors.append(where + "has no " + title + " section")
        if not any(STORY_HEADING.match(title) for title in present):
            errors.append(where + "tells no story — a requirement wants at least one")

        for verdict in verification_verdicts(detail.body):
            if verdict not in DETAIL_VERDICTS:
                errors.append(where + "records the verdict " + verdict + ", not one of " + ", ".join(DETAIL_VERDICTS))

    seen = {}
    for detail in data.details:
        if detail.ident in seen:
            errors.append(detail.path + ": " + detail.ident + " is already detailed by " + seen[detail.ident])
        seen[detail.ident] = detail.path

    # Off by default, because turning it on with a backlog fails the gate for work nobody has been
    # asked for yet. It is what closes the track once the backlog is cleared.
    if spec.get("require_detail_for_satisfied"):
        for ident in sorted(satisfied & eligible):
            if ident not in seen:
                errors.append(ident + " is satisfied and has no detail file under " + directory)
    return errors


# --------------------------------------------------------------------------------------------
# Source 6 — manual test scenarios
# --------------------------------------------------------------------------------------------
#
# One file per requirement again, and it is not a second detail file. The detail file settles what
# a requirement *means*; this holds what somebody does at a keyboard to find out whether it holds.
# The two are separated because the readers are: what a requirement means is the specification
# owner's argument, and what a session covers is the test manager's.
#
# Two properties are worth a check rather than a convention, because both fail silently:
#
# 1. **Whoever runs these has the product and nothing else.** A scenario carrying a command is one
#    nobody on the test team can run, and a file of them looks like coverage while producing none.
#    Setup that genuinely needs a command belongs under *Before you start*.
# 2. **A file of nothing but happy paths.** It is the natural thing to write and the least useful
#    thing to run: the ways somebody gets a job wrong are most of what a manual session finds.

SCENARIO_STATUSES = ("draft", "reviewed")
SCENARIO_RESULTS = ("pass", "fail", "blocked")
SCENARIO_TYPES = (
    "happy path",
    "negative",
    "permission",
    "another tenant",
    "repeat",
    "at once",
    "boundary",
)
SCENARIO_KEYS = (
    "id",
    "area",
    "status",
    "written_by",
    "approved_by",
    "detail_status",
    "detail_read_on",
    "areas",
)
SCENARIO_SECTIONS = (
    "The requirement",
    "Before you start",
    "Scenarios",
    "Not testable yet",
    "Related",
    "Runs",
)

# Normalised, so `### S1 — opening a second branch` arrives as `s1openingasecondbranch` and the
# digit is what distinguishes a scenario from a subsection that happens to start with an s.
SCENARIO_HEADING = re.compile(r"^s\d")
FIELD = r"\*\*{}\*\*\s*(?P<value>[^·|\n]+)"
# What a tester cannot do. Deliberately literal: the point is not to catch every command ever
# written but the shapes that actually appear when somebody drafts from a slice demo — a shell
# prompt, the database client, the stack, an HTTP call — plus the project's own tools by name,
# from `scenarios.commands`.
COMMAND_SHAPES = r"^\s*\$\s|\bpsql\b|\bdocker\s+compose\b|\bcurl\s"
ESCAPE_HATCH = "notthroughthescreen"
DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def command_pattern(names) -> re.Pattern:
    """The generic shapes, plus `<name> <subcommand>` for each of the project's own tools."""
    own = [r"\b" + re.escape(str(n)) + r"\s+[a-z][a-z-]*" for n in names if str(n).strip()]
    return re.compile("|".join([COMMAND_SHAPES] + own), re.M)


@dataclass
class Scenarios:
    path: str
    ident: str
    data: dict
    body: str


def parse_scenarios(root: str, directory: str) -> list:
    if not directory:
        return []
    found = []
    for path in sorted(glob.glob(os.path.join(root, directory, "**", "*.md"), recursive=True)):
        if os.path.basename(path).lower() == "readme.md":
            continue
        data, body = parse_front_matter(read(path))
        found.append(
            Scenarios(
                path=os.path.relpath(path, root),
                ident=os.path.splitext(os.path.basename(path))[0],
                data=data,
                body=body,
            )
        )
    return found


def scenario_blocks(body: str) -> list:
    """(name, text) per `### S1 …` under *Scenarios*.

    Split rather than matched, so a check can be about one scenario and say which."""
    lines = section_lines(body, SCENARIO_SECTIONS[2])
    starts = [(i, raw) for i, depth, raw in headings(lines) if depth == 3]
    blocks = []
    for position, (index, raw) in enumerate(starts):
        end = starts[position + 1][0] if position + 1 < len(starts) else len(lines)
        blocks.append((raw.strip(), "\n".join(lines[index + 1 : end])))
    return blocks


def field_of(block: str, name: str) -> str:
    hit = re.search(FIELD.format(name), block)
    return bare(hit.group("value")) if hit else ""


def run_results(body: str) -> list:
    """The third cell of every row under *Runs*. A vocabulary rather than prose: *mostly fine* is
    the result this exists to refuse, because nobody downstream can act on it."""
    found, in_table = [], False
    for line in section_lines(body, SCENARIO_SECTIONS[-1]):
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        if is_separator(line):
            continue
        col = cells(line)
        if len(col) < 3:
            continue
        if bare(col[0]).lower() == "date":
            in_table = True
            continue
        if in_table and bare(col[0]):
            found.append(bare(col[2]))
    return found


def check_scenarios(config: dict, data: Collected) -> list:
    """Every way a scenarios file can be unrunnable by the person it was written for."""
    spec = config.get("scenarios") or {}
    directory = spec.get("dir") or ""
    if not directory:
        return []

    families = [str(f) for f in (spec.get("families") or [])]
    eligible = {i for fam, ids in data.ids.items() for i in ids if not families or fam in families}
    detail_of = {d.ident: d for d in data.details}
    detail_dir = (config.get("requirements") or {}).get("dir") or ""
    command_line = command_pattern(spec.get("commands") or [])
    errors = []

    for file in data.scenarios:
        where = file.path + ": "
        if not file.data:
            errors.append(where + "has no front matter")
            continue

        ident = file.ident
        if scalar(file.data.get("id")) != ident:
            errors.append(where + "declares id " + scalar(file.data.get("id")) + " and is filed as " + ident)
        if ident not in eligible:
            declared = {i for ids in data.ids.values() for i in ids}
            if ident in declared:
                errors.append(where + ident + " belongs to no family the scenario track covers (" + ", ".join(families) + ")")
            else:
                errors.append(where + ident + " is not declared in the specification")
            continue

        area = area_of(ident)
        leaf = os.path.basename(os.path.dirname(file.path))
        if leaf != area:
            errors.append(where + "sits under " + leaf + " and its identifier files under " + area)
        if scalar(file.data.get("area")) != area:
            errors.append(where + "declares area " + scalar(file.data.get("area")) + " and its identifier files under " + area)

        for key in (k for k in SCENARIO_KEYS if k != "approved_by"):
            if scalar(file.data.get(key)).strip() in BLANK:
                errors.append(where + "front matter has no " + key)

        status = scalar(file.data.get("status"))
        if status not in SCENARIO_STATUSES:
            errors.append(where + "status is " + (status or "empty") + ", not one of " + ", ".join(SCENARIO_STATUSES))
        if status == "reviewed" and scalar(file.data.get("approved_by")).strip() in BLANK:
            errors.append(where + "is reviewed and names no approver — a review nobody signed is a draft")

        # **The detail file is the source, and there is no writing scenarios without one.** The
        # requirement's row is one line; inventing the actors and the boundary from it is the
        # guessing the detail track exists to stop, and it would be invisible here.
        detail = detail_of.get(ident)
        if detail is None:
            errors.append(
                where + "has no detail file under " + (detail_dir or "the requirement directory")
                + " — scenarios are written from one, never from the requirement's own line"
            )
        else:
            said = scalar(file.data.get("detail_status"))
            now = scalar(detail.data.get("status"))
            if said and now and said != now:
                errors.append(
                    where + "was written against a " + said + " detail file and " + detail.path
                    + " now reads " + now + " — re-read it, correct the cases and re-date "
                    "detail_read_on"
                )
        read_on = scalar(file.data.get("detail_read_on")).strip()
        if read_on not in BLANK and not DATE.match(read_on):
            errors.append(where + "detail_read_on is " + read_on + ", which is not a date")
        elif detail is not None and read_on not in BLANK:
            # The return path, enforced: a detail file amended after these cases were read fails
            # them, whether or not its status moved. ISO dates compare as strings.
            revised = scalar(detail.data.get("revised_on")).strip()
            if DATE.match(revised) and revised > read_on:
                errors.append(
                    where + "was read from " + detail.path + " on " + read_on + ", and that file was "
                    "revised on " + revised + " — re-read it, correct the cases and re-date detail_read_on"
                )

        row = data.rows.get(ident) or []
        source = bare(row[1]) if len(row) > 1 else ""
        if source and re.sub(r"\s+", " ", source) != bare(quoted(file.body)):
            errors.append(
                where + "quotes " + ident + " differently from the specification. The requirement "
                "was amended, or the quote was edited — re-read it and correct the quote"
            )

        present = section_titles(file.body)
        for title in SCENARIO_SECTIONS:
            if normalise(title) not in present:
                errors.append(where + "has no " + title + " section")

        blocks = [b for b in scenario_blocks(file.body) if SCENARIO_HEADING.match(normalise(b[0]))]
        if not blocks:
            errors.append(where + "carries no scenario — a requirement wants at least one")

        kinds = []
        for name, block in blocks:
            label = name.strip("# ").strip()
            kind = field_of(block, "Type")
            if not kind:
                errors.append(where + label + " declares no Type")
            elif kind not in SCENARIO_TYPES:
                errors.append(where + label + " is a " + kind + " scenario, not one of " + ", ".join(SCENARIO_TYPES))
            else:
                kinds.append(kind)

            ready = field_of(block, "Ready").lower()
            if not ready.startswith("yes") and not ready.startswith("no"):
                errors.append(where + label + " says Ready " + (ready or "nothing") + ", and it is yes or no and why not")

            # A command in a scenario is a scenario nobody on the test team can run.
            hit = command_line.search(block)
            if hit and ESCAPE_HATCH not in normalise(block):
                errors.append(
                    where + label + " asks the tester to run `" + hit.group(0).strip()
                    + "` — a scenario is done through the product's own screens, and setup that "
                    "cannot be belongs under Before you start"
                )

        if kinds and not [k for k in kinds if k != SCENARIO_TYPES[0]]:
            errors.append(
                where + "is every scenario a happy path — the ways somebody gets the job wrong are "
                "most of what a manual session finds"
            )

        for result in run_results(file.body):
            if result not in SCENARIO_RESULTS:
                errors.append(where + "records the result " + result + ", not one of " + ", ".join(SCENARIO_RESULTS))

    seen = {}
    for file in data.scenarios:
        if file.ident in seen:
            errors.append(file.path + ": " + file.ident + " already has scenarios in " + seen[file.ident])
        seen[file.ident] = file.path

    # Off by default, for the same reason the detail track's gate is: turning it on with a backlog
    # fails the gate for work nobody has been asked for yet.
    if spec.get("require_scenarios_for_reviewed_detail"):
        for detail in data.details:
            if detail.ident in eligible and scalar(detail.data.get("status")) == "reviewed" and detail.ident not in seen:
                errors.append(detail.ident + " has a reviewed detail file and no scenarios under " + directory)
    return errors


# --------------------------------------------------------------------------------------------
# Collection
# --------------------------------------------------------------------------------------------


@dataclass
class Collected:
    families: list
    ids: dict  # family -> [ids]
    owner_of: dict  # id -> declaring document
    orders: list
    annotations: list
    rows: dict = field(default_factory=dict)  # id -> the cells of its declaring row
    details: list = field(default_factory=list)
    scenarios: list = field(default_factory=list)
    errors: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    unregistered: list = field(default_factory=list)
    unclaimable: list = field(default_factory=list)


def family_for(ident: str, families: list):
    """Longest prefix wins, so `NFR-OBS-01` resolves to NFR and never to N."""
    for fam in sorted(families, key=lambda f: -len(f.family)):
        if ident.startswith(fam.family + "-"):
            return fam
    return None


def collect(root: str, config: dict) -> Collected:
    registry_path = os.path.join(root, config["registry"])
    if not os.path.exists(registry_path):
        raise SystemExit("error: no registry at " + config["registry"])
    families = parse_registry(read(registry_path))

    ids: dict = {}
    owner_of: dict = {}
    rows: dict = {}
    errors: list = []

    docs_root = os.path.dirname(os.path.join(root, config["registry"]))
    docs_root = os.path.dirname(docs_root) if os.path.basename(docs_root) == "spec" else docs_root

    seen_family = {}
    for fam in families:
        if fam.family in seen_family:
            errors.append(
                "registry declares family " + fam.family + " twice — in the rows owned by "
                + seen_family[fam.family] + " and " + fam.owner
                + ". A family has exactly one declaration site (ID-REGISTRY.md)."
            )
        seen_family[fam.family] = fam.owner

    for fam in families:
        path = os.path.join(docs_root, fam.owner)
        if not os.path.exists(path):
            path = os.path.join(root, fam.owner)
        if not os.path.exists(path):
            if fam.traceable:
                errors.append("registry family " + fam.family + " owns " + fam.owner + ", which does not exist")
            ids[fam.family] = []
            continue
        if os.path.isdir(path):
            # A directory owner (ADRs, one file each) declares identifiers by filename, not by a
            # table. Such a family cannot be traceable: there is no `| ID |` row to read.
            if fam.traceable:
                errors.append("registry family " + fam.family + " owns the directory " + fam.owner + " and cannot be traceable")
            ids[fam.family] = []
            continue
        text = read(path)
        if fam.section.strip() != "*" and not section_lines(text, fam.section):
            # Distinguished from an empty table because the fix is different: a heading the
            # registry names and the document does not carry is a typo in one of the two.
            errors.append(
                "registry family " + fam.family + " is declared in " + fam.owner + " " + fam.section
                + ", and that document has no such heading"
            )
        found = declared_rows(text, fam.section)
        kept = [i for i, _c in found if family_for(i, families) is fam]
        for ident, col in found:
            if family_for(ident, families) is fam:
                rows.setdefault(ident, col)
        for ident in sorted(set(kept)):
            if kept.count(ident) > 1:
                errors.append(
                    ident + " is declared twice in " + fam.owner + " " + fam.section
                    + ". An identifier has exactly one declaration site (ID-REGISTRY.md)."
                )
            owner_of[ident] = fam.owner
        ids[fam.family] = sorted(set(kept))
        if fam.traceable and not ids[fam.family]:
            errors.append("registry declares family " + fam.family + ", which yields no identifiers")

    orders = parse_work_orders(root, config["work_orders"])
    annotations = parse_annotations(root, config["tests"])
    details = parse_details(root, (config.get("requirements") or {}).get("dir") or "")
    scenarios = parse_scenarios(root, (config.get("scenarios") or {}).get("dir") or "")

    return Collected(
        families=families,
        ids=ids,
        owner_of=owner_of,
        orders=orders,
        annotations=annotations,
        rows=rows,
        details=details,
        scenarios=scenarios,
        errors=errors,
    )


# --------------------------------------------------------------------------------------------
# The ledger
# --------------------------------------------------------------------------------------------


@dataclass
class Row:
    ident: str
    status: str
    slices: list
    proofs: list
    unproven: bool


def build_ledger(data: Collected):
    traceable = [f for f in data.families if f.traceable]
    known = {f.family for f in data.families}
    declared = {i for fam in data.ids.values() for i in fam}

    claims_satisfies: dict = {}
    claims_partial: dict = {}
    for order in data.orders:
        for ident in order.satisfies:
            claims_satisfies.setdefault(ident, set()).add(order.slice_id)
        for ident in order.partial:
            claims_partial.setdefault(ident, set()).add(order.slice_id)

    proofs: dict = {}
    for ident, proof, path in data.annotations:
        proofs.setdefault(ident, []).append((proof, path))

    unknown, unregistered = [], {}
    for ident, _proof, path in data.annotations:
        if ident in declared:
            continue
        fam = family_for(ident, data.families)
        if fam is None or fam.family not in known:
            unregistered.setdefault(ident, set()).add(path)
        else:
            unknown.append((path, ident, fam.family))

    unclaimable = {}
    for ident in sorted(set(claims_satisfies) | set(claims_partial)):
        if ident in declared:
            continue
        fam = family_for(ident, data.families)
        who = sorted(claims_satisfies.get(ident, set()) | claims_partial.get(ident, set()))
        if fam is None:
            unclaimable[ident] = who
        else:
            for slice_id in who:
                unknown.append((slice_id, ident, fam.family))

    sections = []
    counts = {SATISFIED: 0, PARTIAL: 0, NONE: 0}
    for fam in traceable:
        rows = []
        for ident in data.ids[fam.family]:
            sats = claims_satisfies.get(ident, set())
            pars = claims_partial.get(ident, set())
            tests = sorted(set(proofs.get(ident, [])))
            if sats and tests:
                status = SATISFIED
            elif sats or pars or tests:
                status = PARTIAL
            else:
                status = NONE
            counts[status] += 1
            rows.append(
                Row(
                    ident=ident,
                    status=status,
                    slices=sorted(sats | pars),
                    proofs=[p for p, _ in tests],
                    unproven=bool(sats) and not tests,
                )
            )
        sections.append((fam, rows))

    return sections, counts, sorted(set(unknown)), unregistered, unclaimable


def render_ledger(config: dict, sections, counts, unregistered, unclaimable, details=(), scenarios=()) -> str:
    out = [
        "<!-- Generated by `python3 scripts/ledger.py ledger`. Do not edit by hand. -->",
        "",
        "# Requirement coverage",
        "",
        "Generated from four sources, none of them a list maintained beside the specification:",
        "",
        "- `" + config["registry"] + "` — which families are traceable",
        "- each family's declaring section — which identifiers exist",
        "- `" + config["work_orders"] + "/*.md` front matter — what each slice claimed",
        "- `[ID]`-annotated test names — what is actually proven",
        "",
        "A claim of `satisfies` with no annotated test behind it is recorded as **partial**, not",
        "satisfied, and listed below. A ledger that believes its own work orders is a spreadsheet.",
        "",
        "| Status | Count |",
        "|---|--:|",
        "| " + MARK[SATISFIED] + " satisfied | " + str(counts[SATISFIED]) + " |",
        "| " + MARK[PARTIAL] + " partial | " + str(counts[PARTIAL]) + " |",
        "| " + MARK[NONE] + " none | " + str(counts[NONE]) + " |",
        "| **total** | **" + str(sum(counts.values())) + "** |",
        "",
    ]

    unproven = [r for _f, rows in sections for r in rows if r.unproven]
    if unproven:
        out += [
            "## Claimed without proof",
            "",
            "A work order claims `satisfies` and no test names the identifier. Downgraded to",
            "partial above, and listed here so the gap is visible rather than averaged away.",
            "",
            "| ID | Claimed by |",
            "|---|---|",
        ]
        out += ["| " + r.ident + " | " + ", ".join(r.slices) + " |" for r in unproven]
        out += [""]

    if unregistered:
        out += [
            "## Annotations outside the registry",
            "",
            "Test names referencing a family the registry does not carry. Not an error — either a",
            "new document needs a registry row, or the reference belongs to a document that owns",
            "no identifiers.",
            "",
            "| ID | Referenced by |",
            "|---|---|",
        ]
        out += ["| " + i + " | " + ", ".join(sorted(p)) + " |" for i, p in sorted(unregistered.items())]
        out += [""]

    if unclaimable:
        out += [
            "## Claims outside the registry",
            "",
            "A work order advances something the registry carries no family for — a process",
            "section, a rule expressed in prose. Recorded so the claim is visible, not lost.",
            "",
            "| Claimed | By |",
            "|---|---|",
        ]
        out += ["| " + i + " | " + ", ".join(w) + " |" for i, w in sorted(unclaimable.items())]
        out += [""]

    spec = config.get("requirements") or {}
    if spec.get("dir"):
        families = [str(f) for f in (spec.get("families") or [])]
        filed = {d.ident: scalar(d.data.get("status")) for d in details}
        wanted = [
            r.ident
            for fam, rows in sections
            for r in rows
            if r.status == SATISFIED and (not families or fam.family in families)
        ]
        missing = [(i, filed.get(i, "none")) for i in wanted if filed.get(i) != "reviewed"]
        out += [
            "## Requirement detail",
            "",
            "One file per requirement under `" + spec["dir"] + "`, saying what it means — the job somebody",
            "is doing, told as stories, with who must be turned away and what happens at the edges. **It is",
            "not a coverage source**: a requirement is proven by its tests. This is what the test scenarios",
            "are written from, and the one `/requirement-verify` walks.",
            "",
            "| Detail files | Count |",
            "|---|--:|",
            "| reviewed | " + str(sum(1 for v in filed.values() if v == "reviewed")) + " |",
            "| draft | " + str(sum(1 for v in filed.values() if v != "reviewed")) + " |",
            "| **total** | **" + str(len(filed)) + "** |",
            "",
        ]
        if missing:
            out += [
                "### Satisfied, and not yet reviewable by hand",
                "",
                "The ledger reads these as `" + MARK[SATISFIED] + "` and no reviewed detail file stands behind",
                "them, so there is nothing for a tester to write a case from and nothing for a verification run",
                "to judge against. The track's backlog, listed rather than averaged away.",
                "",
                "| ID | Detail |",
                "|---|---|",
            ]
            out += ["| " + i + " | " + v + " |" for i, v in missing]
            out += [""]

    qa = config.get("scenarios") or {}
    if qa.get("dir"):
        written = {s.ident: scalar(s.data.get("status")) for s in scenarios}
        # The backlog is measured against the **detail** files rather than against the ledger: a
        # requirement whose meaning is settled and which nobody can be handed a session for is the
        # gap this track exists to close, whether or not any code claims it yet.
        behind = [
            (d.ident, written.get(d.ident, "none"))
            for d in sorted(details, key=lambda d: d.ident)
            if scalar(d.data.get("status")) == "reviewed" and written.get(d.ident) != "reviewed"
        ]
        out += [
            "## Manual test scenarios",
            "",
            "One file per requirement under `" + qa["dir"] + "`, holding what somebody does at a keyboard",
            "to find out whether it holds — through the product's own screens, with no terminal and no",
            "database. **It is not a coverage source either**: it is the session a tester is handed, written",
            "from the detail file and never from the requirement's own line.",
            "",
            "| Scenario files | Count |",
            "|---|--:|",
            "| reviewed | " + str(sum(1 for v in written.values() if v == "reviewed")) + " |",
            "| draft | " + str(sum(1 for v in written.values() if v != "reviewed")) + " |",
            "| **total** | **" + str(len(written)) + "** |",
            "",
        ]
        if behind:
            out += [
                "### Settled, and nobody can be handed a session for it",
                "",
                "The requirement's meaning is agreed — a reviewed detail file stands behind it — and there is",
                "no reviewed set of scenarios, so a tester asked to check it is deciding what to try. The",
                "track's backlog, listed rather than averaged away.",
                "",
                "| ID | Scenarios |",
                "|---|---|",
            ]
            out += ["| " + i + " | " + v + " |" for i, v in behind]
            out += [""]

    out += ["## Coverage", ""]
    for fam, rows in sections:
        out += [
            "### " + fam.family + " — " + fam.kind + " (" + str(len(rows)) + ")",
            "",
            "| ID | Status | Slices | Proof |",
            "|---|:--:|---|---|",
        ]
        for row in rows:
            proof = "<br>".join("`" + escape(p) + "`" for p in row.proofs)
            out.append(
                "| " + row.ident + " | " + MARK[row.status] + " | " + ", ".join(row.slices) + " | " + proof + " |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------------------------
# The queue
# --------------------------------------------------------------------------------------------


def order_slices(orders: list, phases: list):
    """Topological sort of `depends_on`, tie-broken by phase order then slice id.

    Returns (ordered, errors). A dependency on an unknown slice and a cycle are both errors:
    a queue that cannot be linearised is not an ordering, and picking one arbitrarily hides it.
    """
    errors = []
    letters = [p.get("letter", "") for p in phases] if phases else []
    index = {order.slice_id: order for order in orders}

    def rank(order: WorkOrder):
        phase = order.phase or ""
        position = letters.index(phase) if phase in letters else len(letters)
        return (position, order.slice_id)

    incoming = {}
    for order in orders:
        deps = []
        for dep in order.depends_on:
            if dep not in index:
                errors.append(order.path + ": depends_on names " + dep + ", which is not a work order")
            else:
                deps.append(dep)
        incoming[order.slice_id] = set(deps)

    ready = sorted([o for o in orders if not incoming[o.slice_id]], key=rank)
    ordered = []
    while ready:
        current = ready.pop(0)
        ordered.append(current)
        changed = []
        for other in orders:
            if current.slice_id in incoming[other.slice_id]:
                incoming[other.slice_id].discard(current.slice_id)
                if not incoming[other.slice_id]:
                    changed.append(other)
        ready = sorted(ready + changed, key=rank)

    if len(ordered) < len(orders):
        stuck = sorted(o.slice_id for o in orders if o not in ordered)
        errors.append("depends_on forms a cycle among " + ", ".join(stuck))
        ordered += [o for o in orders if o not in ordered]

    return ordered, errors


def render_queue(config: dict, ordered: list) -> str:
    team = config.get("mode") == "team"
    tracked = bool(config.get("tracker"))
    header = (
        "| # | ID | Phase | Size | Dep | Status | "
        + ("Owner | " if team else "")
        + ("Issue | " if tracked else "")
        + "Slice | Advances |"
    )
    rule = "|--:|---|:--:|:--:|:--:|:--:|" + (":--:|" if team else "") + (":--:|" if tracked else "") + "---|---|"
    out = [
        QUEUE_BEGIN,
        "",
        "<!-- Written by `python3 scripts/ledger.py queue` from work-order front matter.",
        "     Edit the work order, not this block. Prose around it is hand-written. -->",
        "",
        header,
        rule,
    ]
    for position, order in enumerate(ordered, start=1):
        advances = ", ".join(order.satisfies + [p + " (partial)" for p in order.partial])
        row = [
            str(position),
            "**" + order.slice_id + "**",
            order.phase,
            order.size,
            order.dep,
            order.status,
        ]
        if team:
            row.append(order.owner or "—")
        if tracked:
            row.append("#" + order.issue if order.issue and order.issue != "—" else "—")
        row += [escape(order.title), advances]
        out.append("| " + " | ".join(row) + " |")
    out += ["", QUEUE_END]
    return "\n".join(out)


def splice_queue(existing: str, block: str):
    """Replace the generated block in place. The surrounding prose is the human's."""
    if QUEUE_BEGIN not in existing or QUEUE_END not in existing:
        return None
    head = existing.split(QUEUE_BEGIN)[0]
    tail = existing.split(QUEUE_END, 1)[1]
    return head + block + tail


# --------------------------------------------------------------------------------------------
# Process checks
# --------------------------------------------------------------------------------------------

# A placeholder is anything in angle brackets that is not markup: `<N>`, `<the gate commands>`,
# `<150>` and `<test:all>` all count. Case is not a signal — the templates use every shape — so the
# exemptions are for what Markdown itself carries: HTML tags, comments, and autolinked URLs.
PLACEHOLDER = re.compile(r"<([^<>\n]{1,80})>")
HTML_TAG = re.compile(r"^/?(?:a|b|i|p|br|hr|em|img|kbd|pre|sub|sup|div|span|code|strong|table|thead|tbody|tr|td|th|ul|ol|li|details|summary)(?:\s[^>]*)?/?$", re.I)


def placeholders(text: str) -> list:
    """Every unresolved `<...>` in `text`, in order, with the brackets kept for the message."""
    found = []
    for match in PLACEHOLDER.finditer(text):
        inner = match.group(1)
        if inner[0] in "!?" or inner[0].isspace() or inner[-1].isspace():
            continue  # a comment, a processing instruction, or `a < b > c` in prose
        if "://" in inner or inner.startswith("mailto:") or re.fullmatch(r"[^\s@]+@[^\s@]+", inner):
            continue  # an autolink
        if HTML_TAG.match(inner):
            continue
        found.append("<" + inner + ">")
    return found
FENCE = re.compile(r"```[^\n]*\n(.*?)```", re.S)
NUMBERED = re.compile(r"^\s*\d+\.\s+\S", re.M)


INLINE_CODE = re.compile(r"`[^`\n]*`")


def prose_lines(text: str):
    """(line number, line) for every line of prose — outside fenced blocks, outside inline code,
    and outside blockquotes.

    Code is notation, not a gap: `/slice-open <id>`, `slice/<ID>-<slug>` and `git diff
    <last-pass>..HEAD` are how a finished document describes a shape, and they must survive. A
    blockquote is guidance that the bootstrap deletes. What is left is where a placeholder to fill
    can only be a placeholder — which is why the templates keep theirs out of backticks."""
    fenced = False
    for number, line in enumerate(text.split("\n"), start=1):
        if re.match(r"^\s*(```|~~~)", line):
            fenced = not fenced
            continue
        if fenced or line.strip().startswith(">"):
            continue
        yield number, INLINE_CODE.sub("`…`", line)


def demo_section(body: str) -> str:
    """The text under the first heading whose title starts with `Demo`."""
    lines = body.split("\n")
    start, level = None, 0
    for index, depth, raw in headings(lines):
        if start is None:
            if normalise(raw).startswith("demo"):
                start, level = index, depth
            continue
        if depth <= level:
            return "\n".join(lines[start + 1 : index])
    return "" if start is None else "\n".join(lines[start + 1 :])


# The statuses that mean somebody has claimed the slice. A `queued` or `blocked` work order is a
# plan, and planning sixty-four issues into a tracker nobody reads is how a tracker stops being read.
TRACKED = ("in-progress", "in-review", "done")


def check_process(root: str, config: dict, data: Collected, unknown, satisfied=frozenset()) -> list:
    errors = list(data.errors)
    errors += check_details(config, data, set(satisfied))
    errors += check_scenarios(config, data)

    for path, ident, fam in unknown:
        errors.append(path + ": [" + ident + "] is not declared in " + fam + "'s section")

    seen = {}
    for order in data.orders:
        if order.slice_id in seen:
            errors.append(order.path + ": slice id " + order.slice_id + " is already used by " + seen[order.slice_id])
        seen[order.slice_id] = order.path

        # An ADR named by a work order exists before implementation starts. A decision recorded
        # after the fact is a justification; the record is only worth keeping if it precedes
        # the code it governs.
        for adr in order.adr:
            number = adr.split("-", 1)[-1]
            here = os.path.join(root, config["decisions"])
            candidates = []
            for stem in (number, adr, adr.lower()):
                candidates += glob.glob(os.path.join(here, stem + "-*.md"))
                candidates += glob.glob(os.path.join(here, stem + ".md"))
            if not candidates:
                errors.append(order.path + ": names " + adr + ", and no such record exists in " + config["decisions"])

        # A slice is not demonstrable in the abstract. Either a script a reader can paste, or
        # numbered steps through an interface with a stated expected observation.
        demo = demo_section(order.body)
        if not demo.strip():
            errors.append(order.path + ": has no Demo section")
        else:
            blocks = [b for b in FENCE.findall(demo) if [l for l in b.split("\n") if l.strip() and not l.strip().startswith("#")]]
            steps = NUMBERED.findall(demo)
            if order.demo == "ui":
                if len(steps) < 2 or "expected" not in demo.lower():
                    errors.append(order.path + ": demo is `ui` and needs numbered steps and an Expected line")
            elif not blocks:
                errors.append(order.path + ": demo is `script` and carries no runnable code block")
            for hit in placeholders(demo):
                errors.append(order.path + ": demo still carries the placeholder " + hit + " — nobody types an identifier")

        # A work order filed under a phase directory must be the phase it declares. The directory
        # is how a person finds it; the front matter is how the queue orders it. When they
        # disagree the queue is right and the reader is wrong, which is the worse way round.
        sub_dir = os.path.dirname(os.path.relpath(order.path, config["work_orders"]))
        if sub_dir and order.phase:
            leaf = os.path.basename(sub_dir)
            if leaf != order.phase:
                errors.append(
                    order.path + ": sits in phase directory " + leaf + " and declares phase " + order.phase
                )

        # The tracker holds narrative and linkage; the work order holds the record. `issue:` is
        # the one place the two are tied together, and it is written at the moment of claiming —
        # so the number is known before the branch exists and the close commit's `Closes #N` has
        # something to resolve. `—` is the grandfathered value: a slice that landed before the
        # tracker did, which no number can be invented for after the fact.
        if config.get("tracker") and order.status in TRACKED:
            if not order.issue:
                errors.append(
                    order.path + ": status is " + order.status + " and it names no issue —"
                    + " open one at the claim and record it as `issue:`"
                )
            elif order.issue != "—" and not order.issue.isdigit():
                errors.append(
                    order.path + ": issue is " + order.issue
                    + ", which is neither a number nor `—` for a slice that predates the tracker"
                )

        if order.status == "done":
            candidates = slice_paths(root, config, order)
            if not any(os.path.exists(c) for c in candidates):
                errors.append(
                    order.path + ": status is done and " + os.path.relpath(candidates[0], root) + " does not exist"
                )

    limit = int(config.get("wip_limit") or 0)
    if limit:
        active = [o for o in data.orders if o.status in ("in-progress", "in-review")]
        if len(active) > limit:
            errors.append("work in progress is " + str(len(active)) + ", over the limit of " + str(limit))
        for i, one in enumerate(active):
            for other in active[i + 1 :]:
                shared = sorted(set(one.touches) & set(other.touches))
                if shared:
                    errors.append(
                        one.slice_id + " and " + other.slice_id + " are both active and both touch "
                        + ", ".join(shared) + " — serialise them or split the surface"
                    )

    scan = config.get("placeholder_scan", {})
    for path in iter_files(root, scan.get("include", []), scan.get("exclude", [])):
        for line_no, line in prose_lines(read(path)):
            for hit in placeholders(line):
                errors.append(
                    os.path.relpath(path, root) + ":" + str(line_no) + ": unresolved placeholder " + hit
                )

    return errors


# --------------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------------


def write_or_check(root: str, rel: str, content: str, check: bool) -> list:
    path = os.path.join(root, rel)
    if check:
        current = read(path) if os.path.exists(path) else ""
        if current != content:
            return [rel + " is stale. Run `python3 scripts/ledger.py`."]
        return []
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return []


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Coverage ledger, slice queue, and process checks.")
    parser.add_argument("command", nargs="?", default="all", choices=["all", "ledger", "queue", "check"])
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--root", default=".", help="project root")
    parser.add_argument("--config", default="scripts/ledger.config.json")
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    config = load_config(root, args.config)
    verify = args.check or args.command == "check"

    data = collect(root, config)
    sections, counts, unknown, unregistered, unclaimable = build_ledger(data)
    ordered, order_errors = order_slices(data.orders, config.get("phases", []))

    errors = []
    if args.command in ("all", "ledger", "check"):
        errors += write_or_check(
            root,
            config["coverage_out"],
            render_ledger(config, sections, counts, unregistered, unclaimable, data.details, data.scenarios),
            verify,
        )

    if args.command in ("all", "queue", "check"):
        queue_path = os.path.join(root, config["queue_out"])
        if not os.path.exists(queue_path):
            errors.append(config["queue_out"] + " does not exist")
        else:
            spliced = splice_queue(read(queue_path), render_queue(config, ordered))
            if spliced is None:
                errors.append(config["queue_out"] + " has no " + QUEUE_BEGIN + " … " + QUEUE_END + " block")
            else:
                errors += write_or_check(root, config["queue_out"], spliced, verify)

    errors += order_errors
    if args.command == "check":
        satisfied = {r.ident for _f, rows in sections for r in rows if r.status == SATISFIED}
        errors += check_process(root, config, data, unknown, satisfied)
    else:
        errors += [p + ": [" + i + "] is not declared in " + f + "'s section" for p, i, f in unknown]
        errors += data.errors

    for message in sorted(set(errors)):
        sys.stderr.write("error: " + message + "\n")

    if not errors and args.command in ("all", "ledger", "check"):
        sys.stdout.write(
            "coverage: " + str(counts[SATISFIED]) + " satisfied, " + str(counts[PARTIAL]) + " partial, "
            + str(counts[NONE]) + " none, " + str(sum(counts.values())) + " total\n"
        )
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
