#!/usr/bin/env python3
"""Traceability tooling: the coverage ledger, the slice queue, and the process checks.

Generated by the `bootstrap` kit. Stdlib only, Python 3.9+.

    python3 scripts/ledger.py                    write the ledger and the queue block
    python3 scripts/ledger.py ledger [--check]   just the coverage ledger
    python3 scripts/ledger.py queue  [--check]   just the generated queue block
    python3 scripts/ledger.py check              verify both, plus every process check — CI runs this

The contract, in one paragraph. `ID-REGISTRY.md` declares identifier *families* — never
identifiers. Each family names the document and the section that declares its IDs. An identifier
is declared if and only if it is the first cell of a table row, under a header row beginning
`| ID |`, inside that section. Work orders claim IDs in their YAML frontmatter. Tests prove them
by carrying `[ID]` in a test name. This tool joins the four sources and writes the result down.

Nothing here knows a prefix. Adding a family is a Markdown row, never a code change.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from dataclasses import dataclass, field

# --------------------------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------------------------

DEFAULTS = {
    "project": "",
    "mode": "solo",
    "registry": "docs/spec/ID-REGISTRY.md",
    "work_orders": "docs/process/work-orders",
    "slices": "docs/process/slices",
    "decisions": "docs/decisions",
    "coverage_out": "docs/process/COVERAGE.md",
    "queue_out": "docs/process/SLICE-QUEUE.md",
    "tests": {
        "globs": ["**/*.test.*", "**/test_*.py", "**/*_test.go"],
        "exclude": ["**/node_modules/**", "**/.venv/**", "**/dist/**", "**/build/**"],
        "annotation": r"\[(?P<id>[A-Za-z][A-Za-z0-9]*(?:-[A-Za-z0-9.]+)+)\]",
    },
    "placeholder_scan": {
        "include": ["docs/**/*.md", "CLAUDE.md", "README.md"],
        "exclude": ["docs/process/templates/**", "docs/decisions/template.md"],
    },
    "phases": [],
    "wip_limit": 0,
    # The detail track is off until a project installs it: an empty `dir` means the checks below
    # never run, so a project that declined it is not failed for a directory it does not have.
    "requirements": {
        "dir": "",
        "families": [],
        "phase_pattern": "V1|V2|R",
        "require_detail_for_satisfied": False,
    },
}

QUEUE_BEGIN = "<!-- generated:queue -->"
QUEUE_END = "<!-- /generated -->"

SATISFIED, PARTIAL, NONE = "satisfied", "partial", "none"
MARK = {SATISFIED: "●", PARTIAL: "◐", NONE: "○"}


def load_config(root: str, path: str) -> dict:
    """Read `scripts/ledger.config.json`, merged one level deep over the defaults."""
    merged = json.loads(json.dumps(DEFAULTS))
    full = os.path.join(root, path)
    if os.path.exists(full):
        with open(full, encoding="utf-8") as handle:
            raw = json.load(handle)
        for key, value in raw.items():
            if isinstance(value, dict) and isinstance(merged.get(key), dict):
                merged[key].update(value)
            else:
                merged[key] = value
    return merged


# --------------------------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------------------------


def bare(cell: str) -> str:
    """Strip emphasis and code fencing from a table cell so `**INV-1**` reads as `INV-1`."""
    return cell.replace("*", "").replace("`", "").strip()


def normalise(heading: str) -> str:
    """Lowercase, alphanumerics only — so `§9 Functional requirements` finds `## 9. Functional
    requirements`. The registry stays readable; the matcher does the work."""
    return re.sub(r"[^a-z0-9]", "", heading.lower())


def cells(line: str) -> list:
    """Split a Markdown table row into its cells."""
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|"):
        body = body[:-1]
    return [c.strip() for c in body.split("|")]


def is_separator(line: str) -> bool:
    return bool(re.match(r"^\s*\|[\s:|-]+\|\s*$", line))


def escape(text: str) -> str:
    return text.replace("|", "\\|").strip()


def headings(lines) -> list:
    """(index, level, title) for every heading, ignoring anything inside a fenced code block.

    A shell comment inside a ```bash block matches the heading pattern exactly. Reading one as a
    heading truncates whatever section it sits in, which is how a demo script full of `#` comments
    becomes an empty demo section."""
    found, fenced = [], False
    for index, line in enumerate(lines):
        if re.match(r"^\s*(```|~~~)", line):
            fenced = not fenced
            continue
        if fenced:
            continue
        head = re.match(r"^(#{1,6})\s+(.*)$", line)
        if head:
            found.append((index, len(head.group(1)), head.group(2)))
    return found


def read(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def iter_files(root: str, includes, excludes=()) -> list:
    """Expand glob patterns relative to `root`, deterministically, honouring exclusions."""
    excluded = set()
    for pattern in excludes:
        excluded.update(glob.glob(os.path.join(root, pattern), recursive=True))
    found = set()
    for pattern in includes:
        for hit in glob.glob(os.path.join(root, pattern), recursive=True):
            if os.path.isfile(hit) and hit not in excluded:
                found.add(hit)
    return sorted(found)


# --------------------------------------------------------------------------------------------
# A minimal YAML front-matter reader
# --------------------------------------------------------------------------------------------
#
# Deliberately not a YAML implementation. Work-order front matter is scalars, inline lists and
# block lists, and nothing else — a restriction the template states and this parser enforces by
# not understanding anything more. A dependency for eight fields would be the wrong trade.


def strip_comment(raw: str) -> str:
    """Drop a trailing `# ...` comment, as YAML does — a `#` opens one only after whitespace.

    The templates carry an aligned comment on half their front-matter lines (`status: queued
    # queued | in-progress | ...`), so a drafter who fills one in and leaves the comment is doing
    the obvious thing. Without this, `status` reads as the whole line and every check that compares
    it silently stops working."""
    value = raw.strip()
    if value[:1] in ("\"", "'"):
        end = value.find(value[0], 1)
        if end != -1:
            return value[: end + 1]
        return value
    cut = re.search(r"(?:^|\s)#", value)
    return value[: cut.start()].strip() if cut else value


def parse_scalar(raw: str):
    value = strip_comment(raw)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value in ("true", "false"):
        return value == "true"
    if value in ("null", "~", ""):
        return None
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def parse_front_matter(text: str):
    """Return (mapping, body). A file with no front matter yields ({}, text)."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}, text
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        return {}, text

    data: dict = {}
    key = None
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        item = re.match(r"^\s*-\s+(.*)$", line)
        if item and key is not None:
            data.setdefault(key, [])
            if isinstance(data[key], list):
                data[key].append(parse_scalar(item.group(1)))
            continue
        pair = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$", line)
        if not pair:
            continue
        key, raw = pair.group(1), strip_comment(pair.group(2))
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            data[key] = [parse_scalar(p) for p in inner.split(",")] if inner else []
        elif raw == "":
            data[key] = []
        else:
            data[key] = parse_scalar(raw)
    return data, "\n".join(lines[end + 1 :])


def as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(v) for v in value if v not in (None, "")]
    return [str(value)] if str(value) else []


# --------------------------------------------------------------------------------------------
# Source 1 — the registry
# --------------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Family:
    family: str
    pattern: str
    owner: str
    section: str
    kind: str
    traceable: bool


def parse_registry(text: str) -> list:
    """Read the `| Family | Pattern | Owner | Declared in | Kind | Traceable |` table."""
    families = []
    for line in text.split("\n"):
        if not line.strip().startswith("|") or is_separator(line):
            continue
        col = cells(line)
        if len(col) < 6:
            continue
        name = bare(col[0])
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name) or name.lower() == "family":
            continue
        families.append(
            Family(
                family=name,
                pattern=bare(col[1]),
                owner=bare(col[2]),
                section=bare(col[3]),
                kind=bare(col[4]),
                traceable="yes" in col[5].lower(),
            )
        )
    return families


# --------------------------------------------------------------------------------------------
# Source 2 — declared identifiers
# --------------------------------------------------------------------------------------------


def section_lines(text: str, section: str) -> list:
    """The lines of `section`, from its heading to the next heading of the same or higher level.

    Subsections are included and siblings are not. A section of `*` is the whole document."""
    lines = text.split("\n")
    if section.strip() == "*":
        return lines
    want = normalise(section)
    start = None
    level = 0
    for index, depth, raw in headings(lines):
        title = normalise(raw)
        if start is None:
            if title == want or title.startswith(want) or (title and want.startswith(title)):
                start, level = index, depth
            continue
        if depth <= level:
            return lines[start + 1 : index]
    return [] if start is None else lines[start + 1 :]


def declared_rows(text: str, section: str) -> list:
    """(identifier, cells) for every declaring row, in document order.

    The whole row rather than its first cell, because the requirement's own words are the second
    cell and the detail track quotes them verbatim. Nothing else may restate a requirement: a
    second wording of one is a second requirement, discovered the day the two disagree."""
    found, in_table = [], False
    for line in section_lines(text, section):
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        if is_separator(line):
            continue
        col = cells(line)
        if not col:
            continue
        first = bare(col[0])
        if first.lower() == "id":
            in_table = True
            continue
        if in_table and first:
            found.append((first, col))
    return found


def declared_ids(text: str, section: str) -> list:
    """Every first-cell value of a table whose header row begins `| ID |`, inside `section`."""
    return [ident for ident, _cells in declared_rows(text, section)]


# --------------------------------------------------------------------------------------------
# Source 3 — work-order claims
# --------------------------------------------------------------------------------------------


@dataclass
class WorkOrder:
    path: str
    slice_id: str
    title: str = ""
    phase: str = ""
    size: str = ""
    status: str = "queued"
    dep: str = "—"
    owner: str = ""
    depends_on: list = field(default_factory=list)
    touches: list = field(default_factory=list)
    satisfies: list = field(default_factory=list)
    partial: list = field(default_factory=list)
    adr: list = field(default_factory=list)
    demo: str = ""
    body: str = ""


def parse_work_orders(root: str, directory: str) -> list:
    orders = []
    for path in sorted(glob.glob(os.path.join(root, directory, "*.md"))):
        data, body = parse_front_matter(read(path))
        if not data:
            continue
        stem = os.path.splitext(os.path.basename(path))[0]
        orders.append(
            WorkOrder(
                path=os.path.relpath(path, root),
                slice_id=str(data.get("id") or stem),
                title=str(data.get("title") or ""),
                phase=str(data.get("phase") or ""),
                size=str(data.get("size") or ""),
                status=str(data.get("status") or "queued"),
                dep=str(data.get("dep") or "—"),
                owner=str(data.get("owner") or ""),
                depends_on=as_list(data.get("depends_on")),
                touches=as_list(data.get("touches")),
                satisfies=as_list(data.get("satisfies")),
                partial=as_list(data.get("partial")),
                adr=as_list(data.get("adr")),
                demo=str(data.get("demo") or ""),
                body=body,
            )
        )
    return orders


# --------------------------------------------------------------------------------------------
# Source 4 — test annotations
# --------------------------------------------------------------------------------------------

QUOTED = re.compile(r"""(['"`])(.*?)\1""")


def parse_annotations(root: str, tests: dict) -> list:
    """Every `[ID]` occurrence in a test file, with the enclosing test name as its proof.

    Parsing source text is deliberate: this reports what the suite *claims* to prove. That the
    suite passes is a separate gate step, and conflating the two would let a skipped test count
    as evidence without anyone noticing which of the two failed."""
    pattern = re.compile(tests["annotation"])
    hits = []
    for path in iter_files(root, tests["globs"], tests.get("exclude", [])):
        rel = os.path.relpath(path, root)
        try:
            content = read(path)
        except (UnicodeDecodeError, OSError):
            continue
        for line in content.split("\n"):
            for match in pattern.finditer(line):
                ident = match.group("id")
                proof = match.groupdict().get("proof")
                if not proof:
                    quoted = [q.group(2) for q in QUOTED.finditer(line) if "[" + ident + "]" in q.group(2)]
                    proof = quoted[0] if quoted else line.strip()
                hits.append((ident, proof.strip(), rel))
    return sorted(set(hits))


# --------------------------------------------------------------------------------------------
# Source 5 — requirement detail files
# --------------------------------------------------------------------------------------------
#
# One file per requirement, saying what a person would *see* if it held. It is not a coverage
# source — a requirement is proven by its tests — but it is what a manual test case is written
# from, and what a verification run judges against. Nothing else fills that gap: a slice spans
# several requirements and proves its own claims, not theirs.
#
# The whole risk of a second document per requirement is that it becomes a second specification
# which quietly disagrees with the first. Hence the quote: a detail file carries the requirement's
# own words, character for character, and this checks them. When the specification is amended the
# file fails until somebody has read the amendment.

DETAIL_STATUSES = ("draft", "reviewed")
DETAIL_VERDICTS = ("implemented", "gap", "absent", "detail-wrong")
DETAIL_KEYS = ("id", "area", "status", "drafted_by", "approved_by", "reviewed_against", "surface")
DETAIL_SECTIONS = (
    "The requirement",
    "What it means in the application",
    "Actors",
    "Preconditions and data",
    "Observable behaviour",
    "Boundary and negative cases",
    "Out of scope",
    "Open questions",
    "Related",
    "Verification",
)
BLANK = (None, "", "-", "—", "TBD", "tbd")


@dataclass
class Detail:
    path: str
    ident: str
    data: dict
    body: str


def area_of(ident: str) -> str:
    """`FR-ACC-01` files under `FR-ACC`, `INV-1` under `INV`. The directory is derived from the
    identifier, so it is one less thing to keep in step."""
    return ident.rsplit("-", 1)[0]


def scalar(value) -> str:
    """Front matter yields a list for an empty value and for a bracketed one. Either way a field
    that names nobody reads as blank."""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return "" if value is None else str(value)


def parse_details(root: str, directory: str) -> list:
    if not directory:
        return []
    details = []
    for path in sorted(glob.glob(os.path.join(root, directory, "**", "*.md"), recursive=True)):
        if os.path.basename(path).lower() == "readme.md":
            continue
        data, body = parse_front_matter(read(path))
        details.append(
            Detail(
                path=os.path.relpath(path, root),
                ident=os.path.splitext(os.path.basename(path))[0],
                data=data,
                body=body,
            )
        )
    return details


def quoted(body: str) -> str:
    """The blockquote under *The requirement*, unwrapped to one line.

    Joined and whitespace-collapsed so that wrapping a long requirement across several `>` lines
    is a formatting choice rather than a failure."""
    want, inside, lines = normalise(DETAIL_SECTIONS[0]), False, []
    for line in body.split("\n"):
        if line.lstrip().startswith("#"):
            if lines:
                break
            inside = normalise(line.lstrip("#")) == want
            continue
        if inside and line.strip().startswith(">"):
            lines.append(line.strip()[1:].strip())
        elif lines and not line.strip():
            break
    return re.sub(r"\s+", " ", " ".join(lines)).strip()


def section_titles(body: str) -> list:
    return [normalise(t) for _i, depth, t in headings(body.split("\n")) if depth == 2]


def verification_verdicts(body: str) -> list:
    """The second cell of every row under *Verification*, which is where a run records what it
    found. A vocabulary rather than prose: *mostly works* is the verdict this exists to refuse."""
    found, in_table = [], False
    for line in section_lines(body, DETAIL_SECTIONS[-1]):
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            continue
        if is_separator(line):
            continue
        col = cells(line)
        if len(col) < 2:
            continue
        if bare(col[0]).lower() == "date":
            in_table = True
            continue
        if in_table and bare(col[0]):
            found.append(bare(col[1]))
    return found


def check_details(config: dict, data: Collected, satisfied: set) -> list:
    """Every way a detail file can be wrong about the requirement it names."""
    spec = config.get("requirements") or {}
    directory = spec.get("dir") or ""
    if not directory:
        return []

    families = [str(f) for f in (spec.get("families") or [])]
    eligible = {i for fam, ids in data.ids.items() for i in ids if not families or fam in families}
    phase_pattern = str(spec.get("phase_pattern") or "")
    errors = []

    for detail in data.details:
        where = detail.path + ": "
        if not detail.data:
            errors.append(where + "has no front matter")
            continue

        ident = detail.ident
        if scalar(detail.data.get("id")) != ident:
            errors.append(where + "declares id " + scalar(detail.data.get("id")) + " and is filed as " + ident)
        if ident not in eligible:
            # Two different mistakes, and the difference matters: a withdrawn requirement is
            # struck through and thereby undeclared, so its file has outlived it.
            declared = {i for ids in data.ids.values() for i in ids}
            if ident in declared:
                errors.append(where + ident + " belongs to no family the detail track covers (" + ", ".join(families) + ")")
            else:
                errors.append(where + ident + " is not declared in the specification")
            continue

        area = area_of(ident)
        leaf = os.path.basename(os.path.dirname(detail.path))
        if leaf != area:
            errors.append(where + "sits under " + leaf + " and its identifier files under " + area)
        if scalar(detail.data.get("area")) != area:
            errors.append(where + "declares area " + scalar(detail.data.get("area")) + " and its identifier files under " + area)

        # `approved_by` is the exception: a draft has no approver, and the pair is checked below.
        for key in (k for k in DETAIL_KEYS if k != "approved_by"):
            if scalar(detail.data.get(key)).strip() in BLANK:
                errors.append(where + "front matter has no " + key)

        status = scalar(detail.data.get("status"))
        if status not in DETAIL_STATUSES:
            errors.append(where + "status is " + (status or "empty") + ", not one of " + ", ".join(DETAIL_STATUSES))
        if status == "reviewed" and scalar(detail.data.get("approved_by")).strip() in BLANK:
            errors.append(where + "is reviewed and names no approver — a review nobody signed is a draft")

        row = data.rows.get(ident) or []
        source = bare(row[1]) if len(row) > 1 else ""
        if source and re.sub(r"\s+", " ", source) != quoted(detail.body):
            errors.append(
                where + "quotes " + ident + " differently from the specification. The requirement "
                "was amended, or the quote was edited — re-read it, correct the quote and re-date "
                "reviewed_against"
            )
        # Whatever the declaring table uses to phase its requirements, mirrored. A table that
        # carries no such column — an invariant's, typically — is simply not checked.
        phase = ""
        if phase_pattern:
            phase = next((bare(c) for c in row[1:] if re.fullmatch(phase_pattern, bare(c))), "")
        if phase and scalar(detail.data.get("phase")) != phase:
            errors.append(
                where + "says " + (scalar(detail.data.get("phase")) or "no phase")
                + " and the specification says " + phase
            )

        present = section_titles(detail.body)
        for title in DETAIL_SECTIONS:
            if normalise(title) not in present:
                errors.append(where + "has no " + title + " section")

        for verdict in verification_verdicts(detail.body):
            if verdict not in DETAIL_VERDICTS:
                errors.append(where + "records the verdict " + verdict + ", not one of " + ", ".join(DETAIL_VERDICTS))

    seen = {}
    for detail in data.details:
        if detail.ident in seen:
            errors.append(detail.path + ": " + detail.ident + " is already detailed by " + seen[detail.ident])
        seen[detail.ident] = detail.path

    # Off by default, because turning it on with a backlog fails the gate for work nobody has been
    # asked for yet. It is what closes the track once the backlog is cleared.
    if spec.get("require_detail_for_satisfied"):
        for ident in sorted(satisfied & eligible):
            if ident not in seen:
                errors.append(ident + " is satisfied and has no detail file under " + directory)
    return errors


# --------------------------------------------------------------------------------------------
# Collection
# --------------------------------------------------------------------------------------------


@dataclass
class Collected:
    families: list
    ids: dict  # family -> [ids]
    owner_of: dict  # id -> declaring document
    orders: list
    annotations: list
    rows: dict = field(default_factory=dict)  # id -> the cells of its declaring row
    details: list = field(default_factory=list)
    errors: list = field(default_factory=list)
    warnings: list = field(default_factory=list)
    unregistered: list = field(default_factory=list)
    unclaimable: list = field(default_factory=list)


def family_for(ident: str, families: list):
    """Longest prefix wins, so `NFR-OBS-01` resolves to NFR and never to N."""
    for fam in sorted(families, key=lambda f: -len(f.family)):
        if ident.startswith(fam.family + "-"):
            return fam
    return None


def collect(root: str, config: dict) -> Collected:
    registry_path = os.path.join(root, config["registry"])
    if not os.path.exists(registry_path):
        raise SystemExit("error: no registry at " + config["registry"])
    families = parse_registry(read(registry_path))

    ids: dict = {}
    owner_of: dict = {}
    rows: dict = {}
    errors: list = []

    docs_root = os.path.dirname(os.path.join(root, config["registry"]))
    docs_root = os.path.dirname(docs_root) if os.path.basename(docs_root) == "spec" else docs_root

    seen_family = {}
    for fam in families:
        if fam.family in seen_family:
            errors.append(
                "registry declares family " + fam.family + " twice — in the rows owned by "
                + seen_family[fam.family] + " and " + fam.owner
                + ". A family has exactly one declaration site (ID-REGISTRY.md)."
            )
        seen_family[fam.family] = fam.owner

    for fam in families:
        path = os.path.join(docs_root, fam.owner)
        if not os.path.exists(path):
            path = os.path.join(root, fam.owner)
        if not os.path.exists(path):
            if fam.traceable:
                errors.append("registry family " + fam.family + " owns " + fam.owner + ", which does not exist")
            ids[fam.family] = []
            continue
        if os.path.isdir(path):
            # A directory owner (ADRs, one file each) declares identifiers by filename, not by a
            # table. Such a family cannot be traceable: there is no `| ID |` row to read.
            if fam.traceable:
                errors.append("registry family " + fam.family + " owns the directory " + fam.owner + " and cannot be traceable")
            ids[fam.family] = []
            continue
        text = read(path)
        if fam.section.strip() != "*" and not section_lines(text, fam.section):
            # Distinguished from an empty table because the fix is different: a heading the
            # registry names and the document does not carry is a typo in one of the two.
            errors.append(
                "registry family " + fam.family + " is declared in " + fam.owner + " " + fam.section
                + ", and that document has no such heading"
            )
        found = declared_rows(text, fam.section)
        kept = [i for i, _c in found if family_for(i, families) is fam]
        for ident, col in found:
            if family_for(ident, families) is fam:
                rows.setdefault(ident, col)
        for ident in sorted(set(kept)):
            if kept.count(ident) > 1:
                errors.append(
                    ident + " is declared twice in " + fam.owner + " " + fam.section
                    + ". An identifier has exactly one declaration site (ID-REGISTRY.md)."
                )
            owner_of[ident] = fam.owner
        ids[fam.family] = sorted(set(kept))
        if fam.traceable and not ids[fam.family]:
            errors.append("registry declares family " + fam.family + ", which yields no identifiers")

    orders = parse_work_orders(root, config["work_orders"])
    annotations = parse_annotations(root, config["tests"])
    details = parse_details(root, (config.get("requirements") or {}).get("dir") or "")

    return Collected(
        families=families,
        ids=ids,
        owner_of=owner_of,
        orders=orders,
        annotations=annotations,
        rows=rows,
        details=details,
        errors=errors,
    )


# --------------------------------------------------------------------------------------------
# The ledger
# --------------------------------------------------------------------------------------------


@dataclass
class Row:
    ident: str
    status: str
    slices: list
    proofs: list
    unproven: bool


def build_ledger(data: Collected):
    traceable = [f for f in data.families if f.traceable]
    known = {f.family for f in data.families}
    declared = {i for fam in data.ids.values() for i in fam}

    claims_satisfies: dict = {}
    claims_partial: dict = {}
    for order in data.orders:
        for ident in order.satisfies:
            claims_satisfies.setdefault(ident, set()).add(order.slice_id)
        for ident in order.partial:
            claims_partial.setdefault(ident, set()).add(order.slice_id)

    proofs: dict = {}
    for ident, proof, path in data.annotations:
        proofs.setdefault(ident, []).append((proof, path))

    unknown, unregistered = [], {}
    for ident, _proof, path in data.annotations:
        if ident in declared:
            continue
        fam = family_for(ident, data.families)
        if fam is None or fam.family not in known:
            unregistered.setdefault(ident, set()).add(path)
        else:
            unknown.append((path, ident, fam.family))

    unclaimable = {}
    for ident in sorted(set(claims_satisfies) | set(claims_partial)):
        if ident in declared:
            continue
        fam = family_for(ident, data.families)
        who = sorted(claims_satisfies.get(ident, set()) | claims_partial.get(ident, set()))
        if fam is None:
            unclaimable[ident] = who
        else:
            for slice_id in who:
                unknown.append((slice_id, ident, fam.family))

    sections = []
    counts = {SATISFIED: 0, PARTIAL: 0, NONE: 0}
    for fam in traceable:
        rows = []
        for ident in data.ids[fam.family]:
            sats = claims_satisfies.get(ident, set())
            pars = claims_partial.get(ident, set())
            tests = sorted(set(proofs.get(ident, [])))
            if sats and tests:
                status = SATISFIED
            elif sats or pars or tests:
                status = PARTIAL
            else:
                status = NONE
            counts[status] += 1
            rows.append(
                Row(
                    ident=ident,
                    status=status,
                    slices=sorted(sats | pars),
                    proofs=[p for p, _ in tests],
                    unproven=bool(sats) and not tests,
                )
            )
        sections.append((fam, rows))

    return sections, counts, sorted(set(unknown)), unregistered, unclaimable


def render_ledger(config: dict, sections, counts, unregistered, unclaimable, details=()) -> str:
    out = [
        "<!-- Generated by `python3 scripts/ledger.py ledger`. Do not edit by hand. -->",
        "",
        "# Requirement coverage",
        "",
        "Generated from four sources, none of them a list maintained beside the specification:",
        "",
        "- `" + config["registry"] + "` — which families are traceable",
        "- each family's declaring section — which identifiers exist",
        "- `" + config["work_orders"] + "/*.md` front matter — what each slice claimed",
        "- `[ID]`-annotated test names — what is actually proven",
        "",
        "A claim of `satisfies` with no annotated test behind it is recorded as **partial**, not",
        "satisfied, and listed below. A ledger that believes its own work orders is a spreadsheet.",
        "",
        "| Status | Count |",
        "|---|--:|",
        "| " + MARK[SATISFIED] + " satisfied | " + str(counts[SATISFIED]) + " |",
        "| " + MARK[PARTIAL] + " partial | " + str(counts[PARTIAL]) + " |",
        "| " + MARK[NONE] + " none | " + str(counts[NONE]) + " |",
        "| **total** | **" + str(sum(counts.values())) + "** |",
        "",
    ]

    unproven = [r for _f, rows in sections for r in rows if r.unproven]
    if unproven:
        out += [
            "## Claimed without proof",
            "",
            "A work order claims `satisfies` and no test names the identifier. Downgraded to",
            "partial above, and listed here so the gap is visible rather than averaged away.",
            "",
            "| ID | Claimed by |",
            "|---|---|",
        ]
        out += ["| " + r.ident + " | " + ", ".join(r.slices) + " |" for r in unproven]
        out += [""]

    if unregistered:
        out += [
            "## Annotations outside the registry",
            "",
            "Test names referencing a family the registry does not carry. Not an error — either a",
            "new document needs a registry row, or the reference belongs to a document that owns",
            "no identifiers.",
            "",
            "| ID | Referenced by |",
            "|---|---|",
        ]
        out += ["| " + i + " | " + ", ".join(sorted(p)) + " |" for i, p in sorted(unregistered.items())]
        out += [""]

    if unclaimable:
        out += [
            "## Claims outside the registry",
            "",
            "A work order advances something the registry carries no family for — a process",
            "section, a rule expressed in prose. Recorded so the claim is visible, not lost.",
            "",
            "| Claimed | By |",
            "|---|---|",
        ]
        out += ["| " + i + " | " + ", ".join(w) + " |" for i, w in sorted(unclaimable.items())]
        out += [""]

    spec = config.get("requirements") or {}
    if spec.get("dir"):
        families = [str(f) for f in (spec.get("families") or [])]
        filed = {d.ident: scalar(d.data.get("status")) for d in details}
        wanted = [
            r.ident
            for fam, rows in sections
            for r in rows
            if r.status == SATISFIED and (not families or fam.family in families)
        ]
        missing = [(i, filed.get(i, "none")) for i in wanted if filed.get(i) != "reviewed"]
        out += [
            "## Requirement detail",
            "",
            "One file per requirement under `" + spec["dir"] + "`, saying what a person would see if it",
            "held — the actors, the preconditions and the observable outcome a manual test case is written",
            "from. **It is not a coverage source**: a requirement is proven by its tests. This is the queue",
            "a tester works from, and the one `/requirement-verify` walks.",
            "",
            "| Detail files | Count |",
            "|---|--:|",
            "| reviewed | " + str(sum(1 for v in filed.values() if v == "reviewed")) + " |",
            "| draft | " + str(sum(1 for v in filed.values() if v != "reviewed")) + " |",
            "| **total** | **" + str(len(filed)) + "** |",
            "",
        ]
        if missing:
            out += [
                "### Satisfied, and not yet reviewable by hand",
                "",
                "The ledger reads these as `" + MARK[SATISFIED] + "` and no reviewed detail file stands behind",
                "them, so there is nothing for a tester to write a case from and nothing for a verification run",
                "to judge against. The track's backlog, listed rather than averaged away.",
                "",
                "| ID | Detail |",
                "|---|---|",
            ]
            out += ["| " + i + " | " + v + " |" for i, v in missing]
            out += [""]

    out += ["## Coverage", ""]
    for fam, rows in sections:
        out += [
            "### " + fam.family + " — " + fam.kind + " (" + str(len(rows)) + ")",
            "",
            "| ID | Status | Slices | Proof |",
            "|---|:--:|---|---|",
        ]
        for row in rows:
            proof = "<br>".join("`" + escape(p) + "`" for p in row.proofs)
            out.append(
                "| " + row.ident + " | " + MARK[row.status] + " | " + ", ".join(row.slices) + " | " + proof + " |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------------------------
# The queue
# --------------------------------------------------------------------------------------------


def order_slices(orders: list, phases: list):
    """Topological sort of `depends_on`, tie-broken by phase order then slice id.

    Returns (ordered, errors). A dependency on an unknown slice and a cycle are both errors:
    a queue that cannot be linearised is not an ordering, and picking one arbitrarily hides it.
    """
    errors = []
    letters = [p.get("letter", "") for p in phases] if phases else []
    index = {order.slice_id: order for order in orders}

    def rank(order: WorkOrder):
        phase = order.phase or ""
        position = letters.index(phase) if phase in letters else len(letters)
        return (position, order.slice_id)

    incoming = {}
    for order in orders:
        deps = []
        for dep in order.depends_on:
            if dep not in index:
                errors.append(order.path + ": depends_on names " + dep + ", which is not a work order")
            else:
                deps.append(dep)
        incoming[order.slice_id] = set(deps)

    ready = sorted([o for o in orders if not incoming[o.slice_id]], key=rank)
    ordered = []
    while ready:
        current = ready.pop(0)
        ordered.append(current)
        changed = []
        for other in orders:
            if current.slice_id in incoming[other.slice_id]:
                incoming[other.slice_id].discard(current.slice_id)
                if not incoming[other.slice_id]:
                    changed.append(other)
        ready = sorted(ready + changed, key=rank)

    if len(ordered) < len(orders):
        stuck = sorted(o.slice_id for o in orders if o not in ordered)
        errors.append("depends_on forms a cycle among " + ", ".join(stuck))
        ordered += [o for o in orders if o not in ordered]

    return ordered, errors


def render_queue(config: dict, ordered: list) -> str:
    team = config.get("mode") == "team"
    header = "| # | ID | Phase | Size | Dep | Status | " + ("Owner | " if team else "") + "Slice | Advances |"
    rule = "|--:|---|:--:|:--:|:--:|:--:|" + (":--:|" if team else "") + "---|---|"
    out = [
        QUEUE_BEGIN,
        "",
        "<!-- Written by `python3 scripts/ledger.py queue` from work-order front matter.",
        "     Edit the work order, not this block. Prose around it is hand-written. -->",
        "",
        header,
        rule,
    ]
    for position, order in enumerate(ordered, start=1):
        advances = ", ".join(order.satisfies + [p + " (partial)" for p in order.partial])
        row = [
            str(position),
            "**" + order.slice_id + "**",
            order.phase,
            order.size,
            order.dep,
            order.status,
        ]
        if team:
            row.append(order.owner or "—")
        row += [escape(order.title), advances]
        out.append("| " + " | ".join(row) + " |")
    out += ["", QUEUE_END]
    return "\n".join(out)


def splice_queue(existing: str, block: str):
    """Replace the generated block in place. The surrounding prose is the human's."""
    if QUEUE_BEGIN not in existing or QUEUE_END not in existing:
        return None
    head = existing.split(QUEUE_BEGIN)[0]
    tail = existing.split(QUEUE_END, 1)[1]
    return head + block + tail


# --------------------------------------------------------------------------------------------
# Process checks
# --------------------------------------------------------------------------------------------

# A placeholder is anything in angle brackets that is not markup: `<N>`, `<the gate commands>`,
# `<150>` and `<test:all>` all count. Case is not a signal — the templates use every shape — so the
# exemptions are for what Markdown itself carries: HTML tags, comments, and autolinked URLs.
PLACEHOLDER = re.compile(r"<([^<>\n]{1,80})>")
HTML_TAG = re.compile(r"^/?(?:a|b|i|p|br|hr|em|img|kbd|pre|sub|sup|div|span|code|strong|table|thead|tbody|tr|td|th|ul|ol|li|details|summary)(?:\s[^>]*)?/?$", re.I)


def placeholders(text: str) -> list:
    """Every unresolved `<...>` in `text`, in order, with the brackets kept for the message."""
    found = []
    for match in PLACEHOLDER.finditer(text):
        inner = match.group(1)
        if inner[0] in "!?" or inner[0].isspace() or inner[-1].isspace():
            continue  # a comment, a processing instruction, or `a < b > c` in prose
        if "://" in inner or inner.startswith("mailto:") or re.fullmatch(r"[^\s@]+@[^\s@]+", inner):
            continue  # an autolink
        if HTML_TAG.match(inner):
            continue
        found.append("<" + inner + ">")
    return found
FENCE = re.compile(r"```[^\n]*\n(.*?)```", re.S)
NUMBERED = re.compile(r"^\s*\d+\.\s+\S", re.M)


INLINE_CODE = re.compile(r"`[^`\n]*`")


def prose_lines(text: str):
    """(line number, line) for every line of prose — outside fenced blocks, outside inline code,
    and outside blockquotes.

    Code is notation, not a gap: `/slice-open <id>`, `slice/<ID>-<slug>` and `git diff
    <last-pass>..HEAD` are how a finished document describes a shape, and they must survive. A
    blockquote is guidance that the bootstrap deletes. What is left is where a placeholder to fill
    can only be a placeholder — which is why the templates keep theirs out of backticks."""
    fenced = False
    for number, line in enumerate(text.split("\n"), start=1):
        if re.match(r"^\s*(```|~~~)", line):
            fenced = not fenced
            continue
        if fenced or line.strip().startswith(">"):
            continue
        yield number, INLINE_CODE.sub("`…`", line)


def demo_section(body: str) -> str:
    """The text under the first heading whose title starts with `Demo`."""
    lines = body.split("\n")
    start, level = None, 0
    for index, depth, raw in headings(lines):
        if start is None:
            if normalise(raw).startswith("demo"):
                start, level = index, depth
            continue
        if depth <= level:
            return "\n".join(lines[start + 1 : index])
    return "" if start is None else "\n".join(lines[start + 1 :])


def check_process(root: str, config: dict, data: Collected, unknown, satisfied=frozenset()) -> list:
    errors = list(data.errors)
    errors += check_details(config, data, set(satisfied))

    for path, ident, fam in unknown:
        errors.append(path + ": [" + ident + "] is not declared in " + fam + "'s section")

    seen = {}
    for order in data.orders:
        if order.slice_id in seen:
            errors.append(order.path + ": slice id " + order.slice_id + " is already used by " + seen[order.slice_id])
        seen[order.slice_id] = order.path

        # An ADR named by a work order exists before implementation starts. A decision recorded
        # after the fact is a justification; the record is only worth keeping if it precedes
        # the code it governs.
        for adr in order.adr:
            number = adr.split("-", 1)[-1]
            here = os.path.join(root, config["decisions"])
            candidates = []
            for stem in (number, adr, adr.lower()):
                candidates += glob.glob(os.path.join(here, stem + "-*.md"))
                candidates += glob.glob(os.path.join(here, stem + ".md"))
            if not candidates:
                errors.append(order.path + ": names " + adr + ", and no such record exists in " + config["decisions"])

        # A slice is not demonstrable in the abstract. Either a script a reader can paste, or
        # numbered steps through an interface with a stated expected observation.
        demo = demo_section(order.body)
        if not demo.strip():
            errors.append(order.path + ": has no Demo section")
        else:
            blocks = [b for b in FENCE.findall(demo) if [l for l in b.split("\n") if l.strip() and not l.strip().startswith("#")]]
            steps = NUMBERED.findall(demo)
            if order.demo == "ui":
                if len(steps) < 2 or "expected" not in demo.lower():
                    errors.append(order.path + ": demo is `ui` and needs numbered steps and an Expected line")
            elif not blocks:
                errors.append(order.path + ": demo is `script` and carries no runnable code block")
            for hit in placeholders(demo):
                errors.append(order.path + ": demo still carries the placeholder " + hit + " — nobody types an identifier")

        if order.status == "done":
            summary = os.path.join(root, config["slices"], order.slice_id + ".md")
            alt = os.path.join(root, config["slices"], order.slice_id.split("-")[-1] + ".md")
            if not os.path.exists(summary) and not os.path.exists(alt):
                errors.append(order.path + ": status is done and " + os.path.relpath(summary, root) + " does not exist")

    limit = int(config.get("wip_limit") or 0)
    if limit:
        active = [o for o in data.orders if o.status in ("in-progress", "in-review")]
        if len(active) > limit:
            errors.append("work in progress is " + str(len(active)) + ", over the limit of " + str(limit))
        for i, one in enumerate(active):
            for other in active[i + 1 :]:
                shared = sorted(set(one.touches) & set(other.touches))
                if shared:
                    errors.append(
                        one.slice_id + " and " + other.slice_id + " are both active and both touch "
                        + ", ".join(shared) + " — serialise them or split the surface"
                    )

    scan = config.get("placeholder_scan", {})
    for path in iter_files(root, scan.get("include", []), scan.get("exclude", [])):
        for line_no, line in prose_lines(read(path)):
            for hit in placeholders(line):
                errors.append(
                    os.path.relpath(path, root) + ":" + str(line_no) + ": unresolved placeholder " + hit
                )

    return errors


# --------------------------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------------------------


def write_or_check(root: str, rel: str, content: str, check: bool) -> list:
    path = os.path.join(root, rel)
    if check:
        current = read(path) if os.path.exists(path) else ""
        if current != content:
            return [rel + " is stale. Run `python3 scripts/ledger.py`."]
        return []
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    return []


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Coverage ledger, slice queue, and process checks.")
    parser.add_argument("command", nargs="?", default="all", choices=["all", "ledger", "queue", "check"])
    parser.add_argument("--check", action="store_true", help="verify without writing")
    parser.add_argument("--root", default=".", help="project root")
    parser.add_argument("--config", default="scripts/ledger.config.json")
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    config = load_config(root, args.config)
    verify = args.check or args.command == "check"

    data = collect(root, config)
    sections, counts, unknown, unregistered, unclaimable = build_ledger(data)
    ordered, order_errors = order_slices(data.orders, config.get("phases", []))

    errors = []
    if args.command in ("all", "ledger", "check"):
        errors += write_or_check(
            root,
            config["coverage_out"],
            render_ledger(config, sections, counts, unregistered, unclaimable, data.details),
            verify,
        )

    if args.command in ("all", "queue", "check"):
        queue_path = os.path.join(root, config["queue_out"])
        if not os.path.exists(queue_path):
            errors.append(config["queue_out"] + " does not exist")
        else:
            spliced = splice_queue(read(queue_path), render_queue(config, ordered))
            if spliced is None:
                errors.append(config["queue_out"] + " has no " + QUEUE_BEGIN + " … " + QUEUE_END + " block")
            else:
                errors += write_or_check(root, config["queue_out"], spliced, verify)

    errors += order_errors
    if args.command == "check":
        satisfied = {r.ident for _f, rows in sections for r in rows if r.status == SATISFIED}
        errors += check_process(root, config, data, unknown, satisfied)
    else:
        errors += [p + ": [" + i + "] is not declared in " + f + "'s section" for p, i, f in unknown]
        errors += data.errors

    for message in sorted(set(errors)):
        sys.stderr.write("error: " + message + "\n")

    if not errors and args.command in ("all", "ledger", "check"):
        sys.stdout.write(
            "coverage: " + str(counts[SATISFIED]) + " satisfied, " + str(counts[PARTIAL]) + " partial, "
            + str(counts[NONE]) + " none, " + str(sum(counts.values())) + " total\n"
        )
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
